### ISSUE TITLE
[GitHub] Unprocessable Entity Error on Events

### ISSUE THREAD

**Issue by teward** [ProgVal/Supybot-plugins#273]
Error and traceback is as follows, and is generated when any event appeared to hit the system.  The initial ping from the webhook, a 'push' item, etc. would all trigger this.

<pre>ERROR 2015-04-04T19:08:46 Cannot connect to git.io: HTTP Error 422: Unprocessable Entity
ERROR 2015-04-04T19:08:46 Uncaught exception in GithubCallback.doPost:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/teward/bots/Supybot-plugins/GitHub/plugin.py", line 146, in doPost
    self.plugin.announce.onPayload(headers, json.loads(form['payload'].value))
  File "/home/teward/bots/Supybot-plugins/GitHub/plugin.py", line 310, in onPayload
    'push', hidden)
  File "/home/teward/bots/Supybot-plugins/GitHub/plugin.py", line 229, in _createPrivmsg
    repl[key + '__branch'] = value.split('/', 2)[2]
AttributeError: 'NoneType' object has no attribute 'split'
ERROR 2015-04-04T19:08:46 Exception id: 0x260d2</pre>

**Comment by w1sht0l1v3** [comment]
https://github.com/ProgVal/Supybot-plugins/blob/master/GitHub/plugin.py#L217
change into if key.endswith('commit__url'):

**Comment by ProgVal** [comment]
It can't fix the issue, it makes the condition more strict, but the line that raises the error is in another block

**Comment by w1sht0l1v3** [comment]
well...it worked for me just fine,else i wouldn't have wrote it :)

**Comment by ProgVal** [comment]
I indeed changed this code recently.
Can you check the error still exists and your fix still fixes it?

**Comment by w1sht0l1v3** [comment]
Well,i downloaded the GitHub plugin last night.
Since i didn't mention earlier,i only get this as an error: "Cannot connect to git.io: HTTP Error 422: Unprocessable Entity".Sorry about not mentioning this.i assumed the error is related to the OP post.
Changing that line i mentioned fixes the quoted error

in case this matters,i'm using this version: The current (running) version of this Supybot is 0.83.4.1+limnoria 2014.07.30, running on Python 2.7.3 (default, Mar 13 2014, 11:03:55)  [GCC 4.7.2].  The newest versions available online are 2015.04.11 (in testing), 2015.03.10 (in master).
